export const markets = [
  {
    marketTitle: "Commodities",
    submarketTitle: "Metals",
    symbol: "frxXAUUSD",
    displayName: "Gold/USD",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Commodities",
    submarketTitle: "Metals",
    symbol: "frxXPDUSD",
    displayName: "Palladium/USD",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Commodities",
    submarketTitle: "Metals",
    symbol: "frxXPTUSD",
    displayName: "Platinum/USD",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Commodities",
    submarketTitle: "Metals",
    symbol: "frxXAGUSD",
    displayName: "Silver/USD",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },

  {
    marketTitle: "cryptocurrencies",
    symbol: "cryBTCUSD",
    displayName: "BTC/USD",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "cryptocurrencies",
    symbol: "cryETHUSD",
    displayName: "ETH/USD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },

  {
    marketTitle: "Derived",
    submarketTitle: "Forex Basket",
    symbol: "WLDAUD",
    displayName: "AUD Basket",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Forex Basket",
    symbol: "WLDEUR",
    displayName: "EUR Basket",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Forex Basket",
    symbol: "WLDGBP",
    displayName: "GBP Basket",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Forex Basket",
    symbol: "WLDUSD",
    displayName: "USD Basket",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Daily Reset Indices",
    symbol: "RDBEAR",
    displayName: "Bear Market Index",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Daily Reset Indices",
    symbol: "RDBULL",
    displayName: "Bull Market Index",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Crash/Boom Indices",
    symbol: "BOOM300N",
    displayName: "Boom 300 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Crash/Boom Indices",
    symbol: "BOOM500",
    displayName: "Boom 500 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Crash/Boom Indices",
    symbol: "BOOM1000",
    displayName: "Boom 1000 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Crash/Boom Indices",
    symbol: "CRASH300N",
    displayName: "Crash 300 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Crash/Boom Indices",
    symbol: "CRASH500",
    displayName: "Crash 500 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Crash/Boom Indices",
    symbol: "CRASH1000",
    displayName: "Crash 1000 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Commodities Basket",
    symbol: "WLDXAU",
    displayName: "Gold Basket",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Jump Indices",
    symbol: "JD10",
    displayName: "Jump 10 Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Jump Indices",
    symbol: "JD25",
    displayName: "Jump 25 Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Jump Indices",
    symbol: "JD50",
    displayName: "Jump 50 Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Jump Indices",
    symbol: "JD75",
    displayName: "Jump 75 Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Jump Indices",
    symbol: "JD100",
    displayName: "Jump 100 Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Step Indices",
    symbol: "stpRNG",
    displayName: "Step 100 Index",
    pip: "0.1",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Step Indices",
    symbol: "stpRNG2",
    displayName: "Step 200 Index",
    pip: "0.1",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Step Indices",
    symbol: "stpRNG5",
    displayName: "Step 500 Index",
    pip: "0.1",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ10V",
    displayName: "Volatility 10 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "R_10",
    displayName: "Volatility 10 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ25V",
    displayName: "Volatility 25 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "R_25",
    displayName: "Volatility 25 Index",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ50V",
    displayName: "Volatility 50 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "R_50",
    displayName: "Volatility 50 Index",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ75V",
    displayName: "Volatility 75 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "R_75",
    displayName: "Volatility 75 Index",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ100V",
    displayName: "Volatility 100 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "R_100",
    displayName: "Volatility 100 Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ150V",
    displayName: "Volatility 150 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Derived",
    submarketTitle: "Continuous Indices",
    symbol: "1HZ250V",
    displayName: "Volatility 250 (1s) Index",
    pip: "0.01",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },

  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxAUDJPY",
    displayName: "AUD/JPY",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxAUDUSD",
    displayName: "AUD/USD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxEURAUD",
    displayName: "EUR/AUD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxEURCAD",
    displayName: "EUR/CAD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxEURCHF",
    displayName: "EUR/CHF",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxEURGBP",
    displayName: "EUR/GBP",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxEURJPY",
    displayName: "EUR/JPY",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxEURUSD",
    displayName: "EUR/USD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxGBPAUD",
    displayName: "GBP/AUD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxGBPJPY",
    displayName: "GBP/JPY",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxGBPUSD",
    displayName: "GBP/USD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxUSDCAD",
    displayName: "USD/CAD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxUSDCHF",
    displayName: "USD/CHF",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Major Pairs",
    symbol: "frxUSDJPY",
    displayName: "USD/JPY",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },

  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxAUDCAD",
    displayName: "AUD/CAD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxAUDCHF",
    displayName: "AUD/CHF",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxAUDNZD",
    displayName: "AUD/NZD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxEURNZD",
    displayName: "EUR/NZD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxGBPCAD",
    displayName: "GBP/CAD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxGBPCHF",
    displayName: "GBP/CHF",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxGBPNOK",
    displayName: "GBP/NOK",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxGBPNZD",
    displayName: "GBP/NZD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxNZDJPY",
    displayName: "NZD/JPY",
    pip: "0.001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxNZDUSD",
    displayName: "NZD/USD",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxUSDMXN",
    displayName: "USD/MXN",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxUSDNOK",
    displayName: "USD/NOK",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxUSDPLN",
    displayName: "USD/PLN",
    pip: "0.0001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
  {
    marketTitle: "Forex",
    submarketTitle: "Minor Pairs",
    symbol: "frxUSDSEK",
    displayName: "USD/SEK",
    pip: "0.00001",
    exchangeIsOpen: "Yes",
    isTradingSuspended: "No",
  },
];
